import Head from "next/head";
import { Box, Flex } from "@chakra-ui/react";
import Background from "@/components/Background";
import Welcome from "@/components/Welcome";
import { useEffect, useState } from "react";
import SingleAuth from "@/modules/auth/SingleAuth";
import Board from "@/modules/board/Board";

export default function Home() {
  const [modal, setModal] = useState("");
  const [player, setPlayer] = useState("");
 
  return (
    <>
      <Head>
        <title>Tic Tac Toe</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box as="main" bg="#f5f5f5" h="100vh" w="full" mx="auto" zIndex={2}>
        <Flex
          w="full"
          h="100vh"
          justifyContent={"center"}
          alignItems={"center"}
        >
          <Background>
            <Welcome setModal={setModal} />
          </Background>
        </Flex>

        <SingleAuth
          setName={setPlayer}
          isOpen={modal === "single"}
          onClose={setModal}
        />
        <Board isOpen={modal === "board"} onClose={setModal} player={player} />
      </Box>
    </>
  );
}
